### ISSUE TITLE
[v1] txhash is different from the displayed txhash 

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnet/godwoken_explorer#348]
https://v1.aggron.gwscan.com/zh-CN/tx/0xd9bc111c572a1c65baccbf71a5adc4ce4e37e383aa7c1e309ed7b1159e02f333
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/32102187/162379001-58e0a0a0-c6eb-4b9a-ba4d-1a3199540085.png">

**Comment by Flouse** [comment]
# Related issue:
- https://github.com/nervosnet/godwoken_explorer/issues/276

## use eth-tx-hash instead of gw-tx-hash
the following api methods will use eth-tx-hash instead of gw-tx-hash both in input params and output return value.
eth_getBlockByHash
eth_getBlockByNumber
eth_getTransactionByHash
eth_getTransactionByBlockHashAndIndex
eth_getTransactionByBlockNumberAndIndex
eth_getTransactionReceipt
eth_getFilterChanges
eth_getLogs
eth_sendRawTransaction

- see: https://github.com/nervosnetwork/godwoken-web3/pull/172

**Comment by Keith-CY** [comment]
There're two hashes pointing to this transaction, the one in URL is a `gw_hash` while the one listed in the page is an `eth_hash`.

It is confusing so we're going to disable visiting transactions of this kind via `gw_hash` and lead users to visit the same transaction by its `eth_hash`

Discussion: https://discordapp.com/channels/956765352514183188/958261584004804650/961886908420612146
